# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: corpinator
  name: microsoft-community-bot
  namespace: microsoft-community
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: corpinator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: corpinator
    spec:
      containers:
      - env:
        - name: BOTSECRETSCONFIG__AKVSECRET
          valueFrom:
            secretKeyRef:
              key: akvsecret
              name: botsecretsconfig
        - name: BOTSECRETSCONFIG__AKVVAULT
          value: https://xbxcommunitydiscord.vault.azure.net/
        - name: BOTSECRETSCONFIG__AKVCLIENTID
          value: d945b08a-986f-4630-a21c-56b4ddb018a8
        - name: BOTSECRETSCONFIG__DEVICEAUTHAPPID
          value: 1a0e1803-97e7-4905-beb8-768fdd9ff8b1
        - name: BOTSECRETSCONFIG__AADTENANT
          value: microsoft.onmicrosoft.com
        image: cisien/corpinator:7
        imagePullPolicy: Always
        name: corpinator
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30