apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: microsoft-community-bot
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: corpinator
    spec:
      containers:
      - name: corpinator
        image: cisien/corpinator:4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
        env:
          - name: BOTSECRETSCONFIG__AKVSECRET
            valueFrom:
              secretKeyRef:
                name: botsecretsconfig
                key: akvsecret
          - name: BOTSECRETSCONFIG__AKVVAULT
            value: https://xbxcommunitydiscord.vault.azure.net/
          - name: BOTSECRETSCONFIG__AKVCLIENTID
            value: d945b08a-986f-4630-a21c-56b4ddb018a8
          - name: BOTSECRETSCONFIG__DEVICEAUTHAPPID
            value: 1a0e1803-97e7-4905-beb8-768fdd9ff8b1
          - name: BOTSECRETSCONFIG__AADTENANT
            value: microsoft.onmicrosoft.com
      nodeSelector:
        beta.kubernetes.io/os: linux